Feature: Switching Accounts on Devnet from ConnectModal
Quantum3-Labs/scaffold-stark-2 pull request #178
Opened 2024-06-26 04:48 UTC by egeaybars123

# Switching Accounts on Devnet

Fixes #163

## Types of change

- [x] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

2024-06-26 20:05 UTC, edulanasca requested changes
The modal is dark when it should be light and otherwise, please modify it

2024-06-26 20:30 UTC, egeaybars123 commented
> The modal is dark when it should be light and otherwise, please modify it. Also don't forget to check lint, types and format so the workflow passes. You can run this line before submitting the commit `yarn next:lint && yarn next:check-types && yarn format && yarn format:check`

Thanks for the review @edulanasca! I did it this way because the ConnectModal's color was the opposite of the theme of the website. I updated the PR according to your requested changes.

2024-06-26 21:22 UTC, edulanasca approved these changes

2024-06-27 01:30 UTC, 0xquantum3labs approved these changes

2024-06-27 01:30 UTC, merged