lint to validate deployContract
Quantum3-Labs/scaffold-stark-2 pull request #198
Opened 2024-07-19 01:01 UTC by edulanasca

# Task name here

Fixes #relevant-issue-here

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

2024-07-19 13:46 UTC, edulanasca commented
Working as expected 
<img width="735" alt="image" src="https://github.com/user-attachments/assets/1897968d-eee6-47a9-bc1b-ca6fa617f033">

2024-07-22 15:43 UTC, edulanasca commented
This commits contains an update for #196.
Now the default state is that a wallet is deployed

2024-07-22 16:28 UTC, jrcarlos2000 requested changes

2024-07-22 16:28 UTC, jrcarlos2000 commented on packages/snfoundry/scripts-ts/deploy.ts
> +  .catch((error) => {
we should keep this section clean , the errors ( with their corresponding messages ) should be thrown on `deploy-contract.ts`

2024-07-23 07:56 UTC, 0xquantum3labs approved these changes

2024-07-23 07:56 UTC, jrcarlos2000 approved these changes

2024-07-23 07:56 UTC, merged