devops(demo): support scaffol-stark-demo workflow
Quantum3-Labs/scaffold-stark-2 pull request #199
Opened 2024-07-19 10:37 UTC by oceanlvr

# Task name here

Workflows / vercel deployment / version control

The final outcome is to have a sample website out of scaffold-stark repo. There are some ways this can be done, we can just add one more workflow to it. This is a simpler approach. 
Or we can have a public repository called scaffol-stark-demo, that is like a website sample out of Scaffold-stark.
Everytime there is an update on the main repo, the workflow should update another scaffol-stark-demo repo and run a workflow on it to deploy it to vercel. 

## Types of change

- [x] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

I choose use env to control the deployed block chain network. It might lead to a bit unmaintainable.

every time we push code to `nextjs` folder on the master branch, it would trigger this pipeline to deploy a new nextjs app on vercel. (using sepolia net)

2024-07-19 10:37 UTC, oceanlvr commented
@jrcarlos2000  PTLA

2024-07-20 09:50 UTC, 0xquantum3labs requested changes

2024-07-20 09:50 UTC, 0xquantum3labs commented on .github/workflows/demo.yaml
> +name: scaffol-stark-demo workflow
typo

2024-07-20 09:50 UTC, 0xquantum3labs commented on .github/workflows/demo.yaml
> +          slack-message: "GitHub build result: ${{ job.status }}\nRepository Name: ${{ github.repository }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
```suggestion
          slack-message: "GitHub deployed to vercel result: ${{ job.status }}\nRepository Name: ${{ github.repository }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
```

2024-07-20 09:50 UTC, 0xquantum3labs commented on .github/workflows/demo.yaml
> +          slack-message: "GitHub build result: ${{ job.status }}\nRepository Name: ${{ github.repository }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
```suggestion
          slack-message: "GitHub deployed to vercel result: ${{ job.status }}\nRepository Name: ${{ github.repository }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
```

2024-07-20 15:43 UTC, jrcarlos2000 approved these changes

2024-07-20 15:43 UTC, 0xquantum3labs approved these changes

2024-07-20 15:43 UTC, merged