Migrated Snfoundry package to support starknet foundry script
Quantum3-Labs/scaffold-stark-2 pull request #223
Opened 2024-07-30 07:26 UTC by Akinbola247

Migrate snfoundry package to fully support Starknet foundry scripts rather than ts-scripts #194

BREAKING CHANGES

Fixes #relevant-issue-here

## Types of change
- [ ] Enhancement

## Comments (optional)
- added feature :
1. Updated starknet devnet to version 0.1.2 in local-devnet folder
2. added cairo script to declare and deploy
3. added starkdeployer command to declare and deploy. `yarn starkdeployer ` or `yarn starkdeployer --network sepolia`
4. added bash script  `deployment.sh` to handle the running of cairoscript, generating _latest.json info, handle --network command, obtain env info & parsing deployment info for use in nextjs 
5. added two more fields in parse-deployment.ts script

- To do 
1. error handling when command fail in deployment.sh and exit with appropriate error message.
2. dynamically obtain contract name rather than hardcoding in deployment.sh
3. obtain owner address from environment variable .env in cairo script instead of hardcoding owner address argument. snforge .env library has incompatibility issue 

- bug 
1. Declaring and deploring at different times require that the cairoscripts_alpha-sepolia_state.json & target folder  be deleted
2. All read functions works on debug contract page but write function in debug contract throws an error.. any comment on this will go a long way... This PR will be kept in draft until it's completed.

2024-08-02 10:37 UTC, 0xquantum3labs commented
Hey @Akinbola247 🙌🏾 Thanks for your contribution this is having a better look now. 

Some TODOs :
- Declare fails on a second run on same network
    - when class already exists
    - If the class already exists just deploy ( not sure how possible is this ) 
    - The autogenerated script.json file is not updated after repeated deploy runs, this is why its failing on NEXTJS because its using a contract deployed on a different instance of devnet which doesnt exist anymore
        - Quick solution delete the file and rerun.
        - Maybe a bug ?
        - we shouldnt commit this run-script.json files , can we pass the folder where these are written to through a cli param like `--output` ?

- Find a way to automate `yarn deploy` without having to add an account , at least on localhost. Maybe generate a scaffold-default account that uses the first private key of localhost chain. 
    - I should be able to do `yarn chain`, `yarn deploy`. And have my contracts ready on UI.
- Try to AVOID as much as we can commands like yarn `deploy:devnet` , we should do `yarn deploy  - -network {devnet | sepolia | mainnet}`
- starknet-devnet-rs version 0.0.4, make sure everything is in same line, as `main` branch uses this version,
- Currently there is `snfoundry-dev/contracts` . Let’s remove this nested folders and pass everything inside `contracts/` to be on `snfoundry/ package.json` and `scarb.toml` & ``snfoundry.toml`` will be on the same folder.

2024-08-07 08:10 UTC, 0xquantum3labs commented
hi @Akinbola247 , let me know when the TODOs are fixed and your branch is updated, and conflicts are resolved  💯

2024-08-07 08:13 UTC, Akinbola247 commented
Oh yes, i will. just one last todo. currently fixing

2024-08-07 15:05 UTC, Akinbola247 commented
due to a bug in sncast_std library, this todo :" When class hash already exists or If the class already exists just deploy" is yet to be completed. When the declare scripts runs the second time, it is bound to fail because the classhash has already been declared which is meant to return a byteArray as an error message. unfortunately, the msg: ByteArray isn't made pub  hence not visible. All things being equal, every other Todos has been completed.

2024-08-08 03:58 UTC, jrcarlos2000 commented
Hello @Akinbola247 , im getting this error when running 

`yarn deploy --network sepolia`

notes :
- I updated my contract source such that the class hash is a new class hash
- i have updated my `.env`
- works well on devnet

<img width="885" alt="image" src="https://github.com/user-attachments/assets/adf67b34-c097-466e-9da0-f4ec043a5ffe">

lets also remove this type of messages that i get when running the script, try to be close to the current messages on `main` branch:

```
command: script run
status: success
command: account add

```

2024-08-08 03:59 UTC, jrcarlos2000 requested changes

2024-08-08 03:59 UTC, jrcarlos2000 commented on packages/snfoundry/scripts-ts/helpers/command.ts
> +  if (network === "sepolia") {
missing "mainnet"

2024-08-08 04:18 UTC, Akinbola247 commented
Alright!, i'll push a fix in a bit. Thanks.

2024-08-08 05:20 UTC, Akinbola247 commented
`command: script run
status: success
command: account add` 
 
The above message cannot be removed, as it is native to sncast

2024-08-08 08:05 UTC, 0xquantum3labs approved these changes

2024-08-08 08:06 UTC, jrcarlos2000 approved these changes

2024-08-08 08:07 UTC, merged