Hooks example page - Issue #215
Quantum3-Labs/scaffold-stark-2 pull request #235
Opened 2024-08-06 09:10 UTC by melnikga

I have added a page with examples of how hooks work, on this page you can get acquainted with the work of such hooks as useScaffoldMultiWriteContract, useScaffoldReadContract, useScaffoldEventHistory, useTargetNetwork, useScaffoldWriteContract

2024-08-06 09:50 UTC, 0xquantum3labs commented
i have changed the base branch to be `hooks-example`

2024-08-09 08:46 UTC, melnikga commented
@0xquantum3labs 
Hey, I've made the necessary changes

2024-08-09 09:07 UTC, jrcarlos2000 requested changes

2024-08-09 09:07 UTC, jrcarlos2000 commented on packages/nextjs/components/HooksExample.tsx
this page is not showing correctly on dark mode.

2024-08-09 09:07 UTC, jrcarlos2000 commented on packages/nextjs/components/HooksExample.tsx
> +    eventName: "GreetingChanged",
```suggestion
    eventName: "GreetingChanged",
``` eventName: "contracts::YourContract::YourContract::GreetingChanged",

2024-08-09 09:07 UTC, jrcarlos2000 commented on packages/nextjs/components/HooksExample.tsx
> +    eventName: "GreetingChanged",
this is the correct usage of `useScaffoldEventHistory` hook.

2024-08-09 09:07 UTC, jrcarlos2000 commented on packages/nextjs/components/HooksExample.tsx
> +  } = useScaffoldEventHistory({
i dont see where the data of `useScaffoldEventHistory` is being used

2024-08-09 09:07 UTC, jrcarlos2000 commented on packages/nextjs/components/HooksExample.tsx
> +        [newGreeting, BigInt(amountEth)],
the correct hook to use here is the `useScaffoldNultiWrite` , because eth has to be approved to spender first , then call `setGreeting()`

2024-08-09 14:15 UTC, melnikga commented
@jrcarlos2000 Fixed everything

2024-08-09 17:11 UTC, gianalarcon approved these changes

2024-08-09 17:13 UTC, merged